version: '3'
services:
  service1:
    image: nginx
    ports:
      - "8081:8090"
  service2:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cas_pratique_clean_archi
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
